### ISSUE TITLE
Single page application and HTML expressions

### ISSUE THREAD

**Issue by hrobarikt** [service-portal/documentation#10]
Hi,
first of all, I would like to thank you for all the effort about building this kind of documentation.
I'm really interested in this new service portal in SNOW and would like to deeply understand all of the features it offers.
Currently I'm a little confused how can I build a true single page application (SPA) using the ngRoute module. Is it possible (and supported) to config all routes in the application using $routeProvider?
Could you please provide a simple example how to achieve this in Service Portal. How could I then reference the template and controller?
And lastly, could you please explain all the new expressions that are used in the html templates like ${expr} or {{::expr}}. I'm familiar with the 2-way databinding but these seems to be a non-angular stuff included by servicenow.
Kind regards,
Tomas

**Comment by deconroy** [comment]
Hi Tomas,
Will try help you out with your second question first:
${expr} will get messages from the sys_ui_message table. {{::expr}} is how you create a one-way binding in angular. i.e. the expression will not change value even if the underlying variable changes.
Hope this helps.
Dan

**Comment by patrickw14** [comment]
Hi Thomas!
For the sake of organization, try to keep it to 1 question/topic per issue, so that it's easier to keep track of everything.

Here are the answers to your questions, though:
1. The only routing that we support in SP is the following: <instance>/<portal_id>?id=<page_id> with URL parameters following it. This form of routing is built in to SP, and you don't need to handle it in any special way. We don't have support for $routeProvider or more complicated routing patterns.
2. The ${message} syntax is our shorthand for internationalizing strings. So, instead of typing ${gs.getMessage(string)} like you would in your Jelly, you just need to type ${string}.
3. {{::expr}} is Angular's one-time binding syntax. For more, see this: http://www.bennadel.com/blog/2759-exploring-one-time-bindings-in-angularjs-1-3.htm

Cheers!
