### ISSUE TITLE
Utilizing ng-change or $watch listener

### ISSUE THREAD

**Issue by infotechconsulting** [service-portal/documentation#12]
When using the ootb widget for "form" (Id=form&table=incident&view=whatever) I'm able to utilize a large majority of Servicenow features like client scripts and UI actions which is great. But from an angularJS perspective, is it possible or what is the best way to utilize ng-change on a field or setting up a watch listen on a form field? I'm wanting to listen for a change without having to reload scope or save a record in order to trigger an event or function. Thank you in advance.

**Comment by iamwill** [comment]
Hello. Thanks for the question. We will clarify this in the documentation. Since the client scripts are run from angular you can just use onChange client scripts. If you make your client script compatible with both desktop and client scripting apis then your app will work on both platforms.

Please reach out to the developer community for more help: https://community.servicenow.com

Best regards.
Will
