### ISSUE TITLE
Link function undocumented

### ISSUE THREAD

**Issue by dmfranko** [service-portal/documentation#123]
I've been unable to find documentation here or on docs.servicenow.com about the intended purpose of the link function is.  I think it's fairly straightforward what it's use is, but it's not obvious by name what its intended use is.

**Comment by patrickw14** [comment]
Since widgets are basically augmented Angular directives, the Link function is used in exactly the same way that Link functions on directives are used in Angular: http://stackoverflow.com/questions/20018507/angularjs-what-is-the-need-of-the-directives-link-function-when-we-already-had

We don't do any additional things with them, and they aren't necessary for 99% of what you probably want to do in your widget. Sometimes, it makes sense to do direct DOM manipulation in a Link function instead of your controller. See the Angular docs for more info!

**Comment by CapaJC** [comment]
No special meaning in ServiceNow beyond AngularJS' use.
https://docs.angularjs.org/guide/directive

**Comment by dmfranko** [comment]
That's fair, I was just thinking even just a super short blurb explaining just that.  Like right now someone has to assume that it means the same thing.

**Comment by patrickw14** [comment]
^ That's a good point, I'll throw in a quick blurb. Thanks!
