### ISSUE TITLE
Using Onload for global/shared functions in catalog client scripts not working

### ISSUE THREAD

**Issue by NYancer3** [service-portal/documentation#185]
We are having some issues with Orchestration-related catalog items in the service portal. The out-of-the-box script includes declare several functions in one onLoad script and attempt to use them in other catalog client scripts. For example, in the variable set "VMware Disks Variables" the client script "VMware disks initialization" declares several functions for showing/hiding various variables. The script "VMWDiskNumOnChangeForCatItemView" then attempts to use those functions, as well as some other variables set in the initial script.

This works fine outisde of the service portal, but it appears that the catalog item widget is somehow scoping the client scripts so that they cannot "see" into on another. Is there a plan to address this, or do we need to make new client scripts just for use in service portal for these items that include the functions that are meant to be shared?

**Comment by zzjasonzz** [comment]
Could the issue be related to accessing variables inside a container?  That was causing us many issues.

**Comment by dylanlindgren** [comment]
This appears to be a scoping issue, and I don't believe what you are doing will be possible within Service Portal.

In the UI16/regular interface, client scripts are output in-line in at the top of the page. For example, an onLoad client script defined like this:

```
function onLoad() {
    console.log('Inside onLoad');
}
```
...is included at the top of the page like this:
```
// other code

function onLoad_14e47562dbc1b2802a0a73b9bf9619cc() {
    console.log('Inside onLoad_14e47562dbc1b2802a0a73b9bf9619cc');
}

// other code
```

The way that multiple client scripts of the same type don't overwrite/re-declare each other (as they all have the name onLoad() in the client script) is that each is renamed based on the SysID of the client script. Interestingly, even the "onLoad" text inside my `console.log` statement is renamed as such. This indicates it must be renaming the function via a simple replace function, and so anywhere the text "onLoad" appears in the client script is replaced by "onLoad_sysid".

The code being declared inline means that if you declared a function outside the onLoad function, but still within the client script field, it would also be in-line. For example:

```
// other code

function onLoad_14e47562dbc1b2802a0a73b9bf9619cc() {
    console.log('Inside onLoad_14e47562dbc1b2802a0a73b9bf9619cc');
}

function myFunction() {
    console.log('Outside onLoad_14e47562dbc1b2802a0a73b9bf9619cc - in custom function');
}

// other code
```
Because this `myFunction()` function is declared in the same scope as the onLoad functions, it means that it is able to be resolved if it's called within one of the onLoad functions (as it's call-site is within a child-scope of where it is declared).

In Service Portal however (which is based on the AngularJS framework), the same client script is included on the page in a wholly different way. AngularJS makes heavy use of scopes, and a lot of parts of the code are included in functions which thus creates a new scope. For example, the same client script looks like below in Service Portal:

```
(function anonymous() {

    function onLoad() {
	console.log('Inside onLoad');
    }

    function myFunction() {
	console.log('Outside onLoad - in custom function');
    }

    return onLoad.apply(this, arguments);

})()
```
As you can see, the client script is wrapped in an immediately-invoked function expression (IIFE), which will have its own scope. If you were to call the `myFunction()` function from a completely different client script (such as an onChange client script) it would not be resolvable, as it's no longer being declared in a parent scope of it's call-site. I guess you could say it's now declared in a "nephew-scope" (if that's even a thing).

I'd highly recommend reading the below free JavaScript book series "You don't know JS" if the above doesn't make sense, or you'd like to understand Service Portal more. In particular, the "Scopes & Closures" one I found incredibly helpful in understanding AngularJS, and thus Service Portal:
https://github.com/getify/You-Dont-Know-JS/tree/master/scope%20%26%20closures

Kind regards,

Dylan Lindgren
Senior Technical Support Engineer | ServiceNow

**Comment by NYancer3** [comment]
Thanks Dylan. I suspected a scoping issue but did not know how the scripts weere invoked within the service portal. That is very helpful to know. I am mostly familiar with scopes as well as the IIFE convention, but I'll take a look at the link you posted as it looks helpful as well.

I think one of my colleagues has reported this through HI and were told that they jsut won't work there. We will ahve to escalate to get the Orchestration scripts updated for compatibility with the Service Portal, as that will be our primary means of publishing our service catalog going forward. In the meantime, we will look at putting in place some consolidated scripts that can be used in the portal.

I appreciate the help.

Thanks,
Nicholas
