### ISSUE TITLE
Ability to setup an angular config module for a Service Portal Application

### ISSUE THREAD

**Issue by digitalbs** [service-portal/documentation#214]
Is it possible to setup an angular config block for a service portal application? I am looking to run an angular provider that will impact my entire service portal application.

**Comment by sasukepatel** [comment]
you can add a JS Include(UI script) to the theme record of a portal.
 
in that UI script you can do like this
 
angular.module('sn.$sp').config(function() {
 
});

i used it to configure angular material themes..not something big like configuring http service as it might conflict with serviceportal backhand code.

https://community.servicenow.com/message/956928#956928

**Comment by iamwill** [comment]
as @sasukepatel you can create an angular config block like that. I don't recommend it though because we own the sn.$sp and we won't support making changes to the application that way.

If you create your own angular module and include it as a dependency you can specify the module name in the sp_dependency record. This is a pretty good alternative that we do support.
