### ISSUE TITLE
Get the approver comments visibled in request item page.

### ISSUE THREAD

**Issue by mohansrinivas91** [service-portal/documentation#220]
In the service portal, the comments entered by the approver is stored under the approval which is related to the RITMbut What we would like to see is for the commets entered by the approver to also be copied over to the notes within the RITM. This way the notes will show in the "Ticket Conversation" widget in Service Portal for end users to see.

Can you pleas ehelp me with this.

**Comment by mandle** [comment]
Mohan,
This is a common requirement. In the past I've leveraged Business Rules to copy comments across related records. 
So in this case a Business Rule on sysapproval_approver that is set to run on update when current.comments.changes() && current.sysapproval.sys_class_name == 'sc_req_item', queries sc_req_item for the RITM, and then sets the sc_req_item.comments.
I recommend prefixing the RITM comments with something like: "Approver Comment: ".

**Comment by mohansrinivas91** [comment]
Yeah, thansk for the response.I haev already created the BR int hat logic but We have an scenario like for a single request many RITM's will be available in that case how we can display the approver comments for the respective item  in RITM page. please advise on the script.

**Comment by mandle** [comment]
Mohan,
I can only point you in the right direction. If the scenario you are describing is one where an "sc_request" approval record's approver comments need to be added to the comments journal on ALL "sc_req_item" records related to it then the Business Rule you've already written can be extended to handle this. The GlideRecord query will be slightly more complex in that it uses the "sysapproval" to return all Requested Items related to the REQ and updates the comments on each.

For additional information I recommend this thread: https://community.servicenow.com/message/972820#972820
Some of the concepts could be applied to your use cases.

@iamwill  This issue can be closed since it's not directly related to Service Portal.

**Comment by mohansrinivas91** [comment]
Hi mandle,

Thanks for the feedback. I just tweaked the B.R. script and it is working fine
