### ISSUE TITLE
Accessing Script Includes/REST/SOAP

### ISSUE THREAD

**Issue by nantu2paul** [service-portal/documentation#27]
First of all "_Awesome Documentation_" guys.

We are trying to migrate our CMS application to Service Portal (it is understood there is no direct migration). Could anyone clear few things for me ?
1. Accessing Script Includes from Client and Server script of Widget ? If yes, an example please.
2. How do we connect REST and SOAP from our Widget scripts ?

**Comment by nathanfirth** [comment]
1) You can just access the script include from the widget server script by instantiating the class and then accessing the methods.
```
var x = new scriptIncludeClassName();
x.callMethodName();
```
I would suggest not calling the script from the controller (client script) because I don't think GlideAjax will work as expected, also it kind of defeats the whole purpose of having the server script at part of the widget.

2) For REST API's I would suggest checking Fred Luddy's post from K16 where he is pulling data from an external service: [https://community.servicenow.com/docs/DOC-5380](https://community.servicenow.com/docs/DOC-5380). Also the Angular $http service supports all the HTTP methods so you could call REST API's straight from Angular. For integrating via SOAP, I would suggest using the SOAP API integration built into ServiceNow instead of trying to do it straight from a Service Portal widget.

**Comment by nantu2paul** [comment]
Thanks @nathanfirth
