### ISSUE TITLE
Localization of Titles

### ISSUE THREAD

**Issue by Snow-Averell** [service-portal/documentation#31]
Is there a concept to localize titles in the SP?

e.g. the page 'requests' is structured like this

![image](https://cloud.githubusercontent.com/assets/19724897/16333507/ea22f8a0-39fb-11e6-9e37-f7954cff114d.png)

The title of the page 'My Requests' is rendered into the header of the result.

![image](https://cloud.githubusercontent.com/assets/19724897/16333586/45abb2fc-39fc-11e6-8766-343318e241f6.png)

But this is not included into the translation mechanism via the sys_ui_message table!!

**Comment by CapaJC** [comment]
sp_page.title is a translated_text field, so it won't take its translation from sys_ui_message. It'll be however translated_text fields normally get translated (I forget that particular mechanism, but it's different).

**Comment by CapaJC** [comment]
I found this:
http://wiki.servicenow.com/index.php?title=Using_Translated_Text#Translating_a_Translated_Text_Field.27s_Content

Now, if that's been done and the Service Portal *still* doesn't show the translation, that's a bug. We should be doing a getDisplayValue on translated_text fields wherever we're showing them to the end user vs. a getValue.

**Comment by Snow-Averell** [comment]
If it is really not accessing the sys_ui_message table then it is an design failure. It can not work with the translated text mechanism, because the table context is missing. There is no nexus between the page and the related table. But the table is of course a key filed: http://wiki.servicenow.com/index.php?title=Using_Translated_Text#Key_Fields_in_the_Translated_Text_.5Bsys_translated_text.5D_Table:

**Comment by CapaJC** [comment]
Perhaps I was unclear. "My Requests" in your example is the value of the sp_page.title field for a specific sp_page record. That field is a translated_text field, so it's display value is managed by the translated text field mechanism described in that wiki link (just like a Module's title, or a Catalog Item's name, etc.), not through the sys_ui_message table.

The only potential bug here would be if the header of that Widget wrongly shows the *value* instead of the *display value* for that field. We'll have a look to see whether that's the case here.

**Comment by CapaJC** [comment]
I've created a card in our VTB to look at this specific issue.

**Comment by yagoferrer** [comment]
I'm closing this issue, unless something else is need it.
