### ISSUE TITLE
Variables with price bug.

### ISSUE THREAD

**Issue by sasukepatel** [service-portal/documentation#33]
i have catalog item named "Sales laptop". there i have one checkbox variable and it has "price if checked" set to value 10.
 
now in serviceportal page if i check the checkbox it is updating the price. but when i uncheck it. it is not decreasing the price.

can you fix this bug?([https://community.servicenow.com/thread/227860])

because of that im trying to update the price manually So im trying to listen for "variable.price.change" event. but this event is getting generated for all types of variables..it should only broadcast for checkbox type variables.

**Comment by CapaJC** [comment]
There is an open Problem for this. It will be fixed, *probably* for Helsinki Patch 3.

--J

On Jun 24, 2016, at 11:07 PM, Rushit Patel <notifications@github.com> wrote:

i have catalog item named "Sales laptop". there i have one checkbox variable and it has "price if checked" set to value 10.

now in serviceportal page if i check the checkbox it is updating the price. but when i uncheck it. it is not decreasing the price.

can you fix this bug?([https://community.servicenow.com/thread/227860])

because of that im trying to update the price manually So im trying to listen for "variable.price.change" event. but this event is getting generated for all types of variables..it should only broadcast for checkbox type variables.

**Comment by sasukepatel** [comment]
ok. Thank you.
