### ISSUE TITLE
sp-dropdown-tree documentation

### ISSUE THREAD

**Issue by pwydra23** [service-portal/documentation#50]
Hi,

Is there any documentation around sp-dropdown-tree? I copied the 'Header Menu' widget, but the angular template spDropdownTreeTemplate did not carry over since the ID needed to be unique.

I cannot find the sp-dropdown-tree code anywhere. How can I re-create that logic with an angular template that has a different name?

Thanks.

**Comment by nathanfirth** [comment]
I think this should be considered a defect and should be fixed in a patch. The spDropdownTree is a directive that lives on the file system that we do not have access to. This makes it very difficult to clone the Header Menu widget. Either convert the directive to an Angular provider that we have access to or create a M2M between the widget and ng_template tables so that cloned widgets could use the same templates.

One workaround is to duplicate the directive as well, it is client side JavaScript so you should be able to find it in your Chrome Dev Tools. But this seems like way to much work just to modify the menu.

My solution was to just write my own header and menu widget.

**Comment by mandle** [comment]
@pwydra23 And now sp_config portal is rendered useless and causes the browser instance to force kill sp_config due to the "id" conflict... right?

**Comment by pwydra23** [comment]
Correct @mandle, in order to get the cloned header menu working - I need to rename the original spDropdownTreeTemplate to something else, an that broke the sp_config site. I need to navigate directly to /$spd.do in order to edit pages.

**Comment by nathanfirth** [comment]
You can find the directive source by going to: instance.service-now.com/scripts/app.$sp/directive.spDropdownTree.js

**Comment by patrickw14** [comment]
You could just find the snDropdownTree directive, turn it into a directive in sp_angular_provider, give it a **different** name (very important for name collision reasons), and use that instead in your header widget.

We're aware of difficulties working with headers and cloning them, and we're working on it (not sure yet what patch it will make it into).

Additionally, we have a number of directives - and spDropdownTree is one of them - that currently live on our file system, meaning they aren't customizable. We understand nobody likes that, and we don't either. We're beginning the process of moving those directives into sp_ng_provider, but we won't know yet what patch those changes will be in since it's a somewhat large refactor. 

That said, as long as you give your replacement directives NEW names, everything should work just fine. 👍

I'll leave this issue open in case there's any further discussion

**Comment by nathanfirth** [comment]
Thanks @patrickw14, you're awesome!

**Comment by gjboulton** [comment]
Just an FYI here.

I posted an issue about adding a Service as an angular provider to a widget that causes a JavaScript error when you’re in edit mode of the page designer. Adding a Directive follows this same process.

In my case the page still worked but I was not able to use the widgets configuration capability due to this error.

I posted this problem in the SNOW Community and received a response this morning that they were able to duplicate the problem and were going to check to see if it’s a known issue.

Kind Regards,

Guy Boulton

[http://uxckeystone.com.au/uploads/emailsignature/uxc-keystone-logo.png]

Consultant



[http://uxckeystone.com.au/uploads/emailsignature/phone.png]

+61 419 604 776

[http://uxckeystone.com.au/uploads/emailsignature/mail.png]

guy.boulton@uxckeystone.com.au<mailto:lyssandro.reis@uxckeystone.com.au>

[http://uxckeystone.com.au/uploads/emailsignature/site.png]

uxckeystone.com.au<http://uxckeystone.com.au/>








The ServiceNow Experts

Stay in touch on

[http://uxckeystone.com.au/uploads/emailsignature/twitter.png]<https://twitter.com/uxckeystone> [http://uxckeystone.com.au/uploads/emailsignature/linkedin.png] <https://www.linkedin.com/company/uxc-keystone>


[http://uxckeystone.com.au/uploads/emailsignature/master-partner.png]

**Comment by Simperdy** [comment]
I just tried to create my own angular directive from the source Nathan posted a link to but can't get the dropdown open on my service portal.

Could some one tell me how to convert the directive to an angular provider directive?
I added the following under angular providers:

Type: Directive
Name: spDropdownCustom

 `/*! RESOURCE: /scripts/app.$sp/directive.spDropdownTree.js */
angular.module('sn.$sp').directive('spDropdownCustom', function () {
return {
restrict: 'E',
scope: {items: '='},
replace: true,
template: '<ul class="dropdown-menu">' +
'<li ng-repeat="mi in items" style="min-width: 20em;" ng-class="{\'dropdown-submenu\': mi.type == \'menu\', \'dropdown-menu-line\':$index < items.length - 1}" ng-include="getURL()">' +
'</ul>',
link : function(scope, element, attrs, controller) {
scope.getURL = function() {
return 'spDropdownTreeTemplate_custom';
}
}
}
});`

I didn't change the lower part of the directive.
In the Header Menu I changed the directive call from <sp-dropdown-tree to <sp-dropdown-custom.
Is there anything else I need to change?

**Comment by Simperdy** [comment]
I found the solution:

Just remove the "angular.module('sn.$sp').directive('spDropdownCustom'," part.

```javascript
/*! RESOURCE: /scripts/app.$sp/directive.spDropdownTree.js */ 
function () {
return {
restrict: 'E',
scope: {items: '='}, replace: true,
template: '<ul class="dropdown-menu">' + '<li ng-repeat="mi in items" style="min-width: 20em;" ng-class="{\'dropdown-submenu\': mi.type == \'menu\', \'dropdown-menu-line\':$index < items.length - 1}" ng-include="getURL()">' + '</ul>',
link : function(scope, element, attrs, controller) { 
scope.getURL = function() {
return 'spDropdownTreeTemplate_custom'; 
} } } };
