### ISSUE TITLE
Service Portal Attachments help

### ISSUE THREAD

**Issue by zzjasonzz** [service-portal/documentation#64]
We have a business rule that prevents certain file extensions from being uploaded in the platform.  The rule has an exception built into it to allow all file types for a specific catalog item that needs to allow executables to be uploaded.

In the service portal I don't see where the specific catalog item is being sent to the server and made available when the business rule runs.  Is there a way to see which catalog item the file is being uploaded for?

I also noticed when the file is first uploaded on a new request form the table is set to sp_portal but after the request is submitted it changes to sc_request.  Where is this change happening and would that help me in my previously stated issue?

**Comment by zzjasonzz** [comment]
I forgot to mention...at this point i had to adjust the bus rule to allow any file types when the table = sp_portal to get it working.  But we don't want to leave it this way.

Also, if a user uploads a file through the SP after the request is submitted we need to be able to apply the same bus rule logic for file extension limitations and be able to allow all for our exception catalog item.

**Comment by zzjasonzz** [comment]
I guess the quick fix is to implement some client side validation in the portal.

**Comment by iamwill** [comment]
Hello. The table change you're noticing is because attachments are first uploaded to sp_portal so we don't lose them and then moved to sc_request after the request is created. This is about to change a bit to the table of the requested item. Please create a problem in HI to track this if it's blocking you. For now checking for the table=sp_portal is the best solution.
