### ISSUE TITLE
Catalog Item -variable type UI Page in Service Portal

### ISSUE THREAD

**Issue by klima** [service-portal/documentation#74]
Hi,
is possible create ui page in catalog item (service portal)? Or something like widget instead ui page?

**Comment by patrickw14** [comment]
You got it - you would make a service portal page instead of a UI page, and you can put existing or custom widgets on that page. Walk through the first few articles here for more info

**Comment by CapaJC** [comment]
The UI Page variable type isn't supported (and won't be, because Jelly), but the UI Macro variable type is supported with one critical caveat: we won't do anything with the UI Macro referenced by the variable, rather you can reference a service portal Widget in that variable type, and the Widget will be included in the catalog item in that position.
