### ISSUE TITLE
Order Guide - Request

### ISSUE THREAD

**Issue by klima** [service-portal/documentation#82]
Hi,
i need more information about creating request in Service Portal OrderGuide.

In widget `SC Order Guide` i can find function:
`$http.post(spUtil.getURL('sc_cat_item_guide'), {"items": $scope.included}).success(function(response) {`

This function create a request and requested items (parameters `items`) by REST. But i need modify a request fields. For example: change `Requested for` and `State` in request form.
How i can do that?

`spUtil.getURL('sc_cat_item_guide')` return somethink like that:
`angular.do?sysparm_type=$sp&sysparm_ck=example_sys_id&type=sc_cat_item_guide`
Where i find documentation for `angular.do` ?

**Comment by jonathanjacob** [comment]
@klima Once the order guide has been submitted, why not use the platform features (business rules, workflow) to handle setting fields on the Request and Item level. If you don't want to do so using the platform, use the Server Script in a Widget to do so, or even via the client using the table API. From my understanding angular.do is an internal SN api that is undocumented.

**Comment by klima** [comment]
Sure, but how to get fields from Order Guide variables in business rules?

**Comment by jonathanjacob** [comment]
on the RITM level you have access to the variable pool, via current.variables._YourVarHere_
You can build some logic into a business rule to spot a order guide item vs. regular items. If you need help doing so look at these SN Guru blog posts:
http://www.servicenowguru.com/system-definition/order-request-items-order-guide/
http://www.servicenowguru.com/system-definition/populate-order-guide-request-ticket/

**Comment by klima** [comment]
I am talking about Request (sc_request) not RITM (sc_req_item).
And not variables in catalog item but variables in OrderGuide.
<img width="1350" alt="zrzut ekranu 2016-08-09 o 21 14 22" src="https://cloud.githubusercontent.com/assets/6649636/17530129/7ecfd25e-5e76-11e6-9285-f961dcfed344.png">

**Comment by jonathanjacob** [comment]
RITM(sc_req_item) has a reference to request on it, which allows for dot walking within business rules (so you could update Request fields from the RITM). 

The variables on an order guide do not get stored unless you "Cascade variables", check off that field on the top right of your screenshot.

See the Wiki for more information about cascading variables:
http://wiki.servicenow.com/index.php?title=Service_Catalog_Order_Guides#Cascading_the_Order_Guide_Variables

See this community post for a similar solution to your request:
https://community.servicenow.com/thread/158562

**Comment by klima** [comment]
Ok thanks. U are sure cascade variables works good in Service Portal?

**Comment by patrickw14** [comment]
Yes - Cascading Variables are supported in Helsinki Patch 2 and above. [https://github.com/service-portal/documentation/blob/c9a4ab2b4cd90ee34df17e3e6271ffa2368b5a8d/documentation/service_catalog_patch2_changes.md](Service Catalog Patch 2 Changes)

**Comment by JeffSalisbury** [comment]
We had an Order Guide implemented for us by Acorio in the Service Portal that is not usable (even after Patch 2) because a copy of all of the variables appears embedded in each and every one of the RITMs. We have had to find a way for our HR team to access the UI16 version of the Order Guide outside of the Service Portal. Hopefully this will be fixed in the next patch.

**Comment by JeffSalisbury** [comment]
To be clear, we had an Order Guide implemented for us by Acorio in the Service Portal that is not usable (even after Patch 2) because a copy of all of the variables appears embedded in each and every one of the RITMs.  We couldn’t hold up our go-live waiting for ServiceNow to fix the inability to hide the variables, so Acorio found a workaround  for our HR team to access the UI16 version of the Order Guide outside of the Service Portal. Hopefully ServiceNow will fix this issue in the next patch so that Order Guides are usable in the Service Portal (it isn’t clear if Patch 3 addresses this issue or not). I don’t personally think it is fair to say that Order Guides are usable while this issue remains.

**Comment by patrickw14** [comment]
@JeffSalisbury Sorry you're having problems! I'm not totally sure what problem you're referring to, but I'd like to help out if I can. Issues here on this GitHub site are meant for issues specifically related to documentation. If you have created an Incident on HI, could you please send me your incident number? That way I can jump in and help out.

**Comment by JeffSalisbury** [comment]
@patrickw14 HI incident INT2985793 was opened by Acorio on our behalf. It has been associated with a generic PRB related to poor performance rather than anything to do with hiding variables. Any help you can provide would be much appreciated.
