### ISSUE TITLE
$sp.logStat

### ISSUE THREAD

**Issue by t1mb0b** [service-portal/documentation#85]
What is the difference between $sp.log and $sp.logStat?

I can't find any info on the logStat function. 

Cheers,

Tim

**Comment by patrickw14** [comment]
$sp.log logs out into the browser console, while $sp.logStat is an internal API that we use to keep track of information like page views, request statistics, things like that. We didn't document it because we didn't think there was much of a reason for anyone to use it, but if you want to use it, let me know and I'll help you out!
